version: ‘3’
services:
  nginx:
    image: nginx:latest
    ports:
      # - "80:80"
      # - "443:443"
    volumes: 
      - "./conf.d:/etc/nginx/conf.d"
  certbot:
    # image: certbot/certbot